Imported Debian version 1.4.8

diff --git a/prepare-release b/prepare-release
--- a/prepare-release
+++ b/prepare-release
@@ -11,18 +11,39 @@ VERSION=$(dpkg-parsechangelog | sed -n -e '/^Version:/s/^Version: //p')
 DISTRIBUTION=$(dpkg-parsechangelog | sed -n -e '/^Distribution:/s/^Distribution: //p')
 
 LIBAPTPKGVERSION="$(awk -v ORS='.' '/^\#define APT_PKG_M/ {print $3}' apt-pkg/contrib/macros.h | sed 's/\.$//')"
-LIBAPTINSTVERSION="$(egrep '^MAJOR=' apt-inst/makefile |cut -d '=' -f 2)"
+LIBAPTINSTVERSION="$(sed -nr 's/set\(MAJOR ([^)]*)\)/\1/p' apt-inst/CMakeLists.txt)"
 
 librarysymbolsfromfile() {
 	local MISSING="$(grep '^+#MISSING' "$1")"
+	local SYMVER="$2"
 	echo '=== Missing optional symbols:'
 	echo -n "$MISSING" | grep '|optional=' || true
 	echo '=== Missing required symbols:'
 	echo -n "$MISSING" | grep -v '|optional=' || true
 	echo '=== New symbols:'
-	grep '^+ ' "$1" | cut -d' ' -f 2 | cut -d'@' -f 1 | c++filt | while read line; do
-		echo " (c++)\"${line}@Base\" $VERSION"
+	grep '^+ ' "$1" | grep -v '^+ (c++' | cut -d' ' -f 2 | cut -d'@' -f 1 | c++filt | while read line; do
+		echo " (c++)\"${line}@${SYMVER}\" $VERSION"
 	done | sort -u
+}
+
+test_deb_control() {
+	echo "Package: apt-test-depends"
+	echo "Version: 1.0"
+	echo "Architecture: all"
+	printf "Depends:"
+	(
+	for i in Build-Depends Build-Depends-Indep Build-Depends-Arch; do
+		grep-dctrl -ns $i -S apt ./debian/control && echo ,
+	done
+		grep-dctrl -ns Depends -F Tests run-tests ./debian/tests/control
+	) | tr '\n' ' '\
+	  | sed -r -e 's#<[^,<>()@]*>##g' \
+	           -e 's#@[^,<>()@]*@##g' \
+	           -e 's#dpkg-dev \([^)]*\)#dpkg-dev#g' \
+	           -e 's#debhelper \([^)]*\)#debhelper#g' \
+	           -e 's#@##g' \
+	           -e 's#,(\s+,)+#, #g' \
+	           -e 's#\s+# #g'
 }
 
 if [ "$1" = 'pre-export' ]; then
@@ -52,17 +73,39 @@ if [ "$1" = 'pre-export' ]; then
 		VERSION="$VERSION~$(date +%Y%m%d)"
 	fi
 
+	sed -i -e "s/^set(PACKAGE_VERSION \".*\")$/set(PACKAGE_VERSION \"${VERSION}\")/" CMakeLists.txt
+	sed -i -e "s/^<!ENTITY apt-product-version \".*\">$/<!ENTITY apt-product-version \"${VERSION}\">/" doc/apt-verbatim.ent
+
+	# update the last-modification field of manpages based on git changes
+	grep --files-with-matches '<date>' doc/*.xml | while read file; do \
+		LASTMOD="$(date -d "@$(git log --format='%at' --max-count=1 --invert-grep --fixed-strings --grep 'review
+typo
+release
+Git-Dch: Ignore' "$file")" '+%Y-%m-%dT00:00:00Z')"
+		sed -i -e "s#^\([ ]\+\)<date>.*</date>\$#\1<date>$LASTMOD</date>#" "$file"
+	done
+
 	if [ "$(date +%Y-%m-%d)" != "$(grep --max-count=1 '^"POT-Creation-Date: .*\n"$' po/apt-all.pot | cut -d' ' -f 2)" -o \
 	     "$(date +%Y-%m-%d)" != "$(grep --max-count=1 '^"POT-Creation-Date: .*\n"$' doc/po/apt-doc.pot | cut -d' ' -f 2)" ]; then
 		echo >&2 'POT files are not up-to-date. Execute »make update-po« for you…'
-		make update-po
+		[ -e build ] || mkdir build
+		( cd build && cmake .. )
+		cmake --build build --target update-po -- -j 4
 	fi
-
-	sed -i -e "s/^PACKAGE_VERSION=\".*\"$/PACKAGE_VERSION=\"${VERSION}\"/" configure.ac
-	sed -i -e "s/^<!ENTITY apt-product-version \".*\">$/<!ENTITY apt-product-version \"${VERSION}\">/" doc/apt-verbatim.ent
+elif [ "$1" = 'pre-build' ]; then
+	if [ "$DISTRIBUTION" = "UNRELEASED" ]; then
+		echo 'BUILDING AN UNRELEASED VERSION'
+	else
+		CONFVERSION="$(sed -ne "s/^set(PACKAGE_VERSION \"\(.*\)\")$/\1/p" CMakeLists.txt)"
+		if [ "$VERSION" != "$CONFVERSION" ]; then
+			echo "changelog (${VERSION}) and CMakeLists.txt (${CONFVERSION}) talk about different versions!"
+			echo "You probably want to run »./prepare-release pre-export« to fix this."
+			exit 1
+		fi
+	fi
 elif [ "$1" = 'post-build' ]; then
 	if [ "$DISTRIBUTION" != "UNRELEASED" ]; then
-		echo >&2 "REMEMBER: Tag this release with »git tag ${VERSION}« if you are satisfied"
+		echo >&2 "REMEMBER: Tag this release with »git tag -s ${VERSION}« if you are satisfied"
 	else
 		echo >&2 'REMEMBER: Change to a valid distribution before release'
 	fi
@@ -94,9 +137,11 @@ elif [ "$1" = 'post-build' ]; then
 		fi
 	done
 	# lets assume we will always have a german manpage translation
-	if [ -e 'doc/de/' ]; then
+	if [ -e */doc/de/ -o -e doc/de ]; then
 		# … but check the translations only with one vendor for translation-specific errors
-		if ! xmllint --nonet --valid --noout $(find doc/ -mindepth 2 -maxdepth 2 -name '*.xml'); then
+		if ! xmllint  --path /vendor/$(./vendor/getinfo current)/ \
+					  --path doc/ \
+					--nonet --valid --noout $(find doc/ */doc/ -mindepth 2 -maxdepth 2 -name '*.xml'); then
 			echo >&2 "WARNING: translated docbook manpages have errors!"
 		fi
 	else
@@ -106,10 +151,22 @@ elif [ "$1" = 'post-build' ]; then
 
 elif [ "$1" = 'library' ]; then
 	librarysymbols() {
-		echo "Checking $1 in version $2"
+		local libname=$(echo "${1}" | cut -c 4-)
+		local buildlib="build/bin/${1}.so.${2}"
+		for dir in $libname */$libname; do
+			local new_buildlib="$dir/${1}.so.${2}"
+			if [  -r "${new_buildlib}" ] && [ ! -e "$buildlib" -o "$new_buildlib" -nt "$buildlib" ]; then
+				local buildlib="${new_buildlib}"
+			fi
+		done
+		if [ ! -r "$buildlib" ]; then
+			echo "ERROR: The library ${1} has to be built before symbols can be checked!"
+			return
+		fi
+		echo "Checking $1 in version $2 build at $(stat -L -c '%y' "$buildlib")"
 		local tmpfile=$(mktemp)
-		dpkg-gensymbols -p${1}${2} -ebuild/bin/${1}.so.${2} -Idebian/${1}${2}.symbols -O/dev/null 2> /dev/null > $tmpfile || true
-		librarysymbolsfromfile "$tmpfile"
+		dpkg-gensymbols -p${1}${2} -e${buildlib} -Idebian/${1}${2}.symbols -O/dev/null 2> /dev/null > $tmpfile || true
+		librarysymbolsfromfile "$tmpfile" "$(echo "${1}" | cut -c 4- | tr -d '-' | tr 'a-z' 'A-Z')_${2}"
 		rm -f $tmpfile
 	}
 	librarysymbols 'libapt-pkg' "${LIBAPTPKGVERSION}"
@@ -117,12 +174,15 @@ elif [ "$1" = 'library' ]; then
 	librarysymbols 'libapt-inst' "${LIBAPTINSTVERSION}"
 elif [ "$1" = 'buildlog' ]; then
 	while [ -n "$2" ]; do
-		librarysymbolsfromfile "$2"
+		librarysymbolsfromfile "$2" 'UNKNOWN'
 		shift
 	done
 elif [ "$1" = 'travis-ci' ]; then
-	apt-get install -q --no-install-recommends $(sed -n -e '/^Build-Depends: /,/^Build-Depends-Indep: / {p}' debian/control | sed -e 's#([^)]*)##g' -e 's#^Build-Depends\(-Indep\)\?: ##' | tr -d ',')
-	apt-get install -q --no-install-recommends $(sed -n 's#^Depends: .*@, \(.*\)$#\1#p' debian/tests/control | tr -d ',')
+	apt-get install -qy --no-install-recommends dctrl-tools equivs gdebi-core moreutils
+
+	test_deb_control > test-control
+	equivs-build test-control
+	gdebi -n apt-test-depends_1.0_all.deb
 elif [ "$1" = 'coverage' ]; then
 	DIR="${2:-./coverage}"
 	git clean -dfX # remove ignored build artefacts for a clean start
@@ -130,8 +190,8 @@ elif [ "$1" = 'coverage' ]; then
 	LCOVRC='--rc geninfo_checksum=1 --rc lcov_branch_coverage=1'
 	mkdir "$DIR"
 	lcov --no-external --directory . --capture --initial --output-file "${DIR}/apt.coverage.init" ${LCOVRC}
-	make test
-	./test/integration/run-tests -q
+	make test || true
+	./test/integration/run-tests -q || true
 	lcov --no-external --directory . --capture --output-file "${DIR}/apt.coverage.run" ${LCOVRC}
 	lcov -a "${DIR}/apt.coverage.init" -a "${DIR}/apt.coverage.run"  -o "${DIR}/apt.coverage.total" ${LCOVRC}
 	cp "${DIR}/apt.coverage.total" "${DIR}/apt.coverage.fixed"
@@ -155,14 +215,79 @@ elif [ "$1" = 'coverage' ]; then
 		   'apt-inst' 'apt-inst/deb' 'apt-inst/contrib' 'apt-private'
 	done
 	genhtml --output-directory "${DIR}" "${DIR}/apt.coverage.fixed" ${LCOVRC}
+elif [ "$1" = 'spellcheckers' ]; then
+	echo '### codespell in source directories:'
+	codespell --enable-colors $(find . -mindepth 1 -maxdepth 1 -type d \! -name '.git' \! -name 'doc' \! -name 'po' \! -name 'build' \! -name 'test') | \
+		grep -v '^.*debian/changelog.*Troup.*==>.*Troupe.*$' || true
+	echo '### codespell in testcases:'
+	codespell $(find test -type f \! -name 'status-*' \! -name 'Packages-*' \! -name '*.deb' \! -name '*.sec' \! -name '*.pub' \! -name '*.db')
+	echo '### codespell in documentation:'
+	codespell doc/*.xml doc/*.txt doc/*.dbk doc/*.ent doc/*.cmake.in doc/xml.add doc/po4a.conf doc/examples doc/po/apt-doc.pot po/apt-all.pot README.* COPYING
+
+	echo '### spellintian in source directories:'
+	{
+		for DIR in $(find . -mindepth 1 -maxdepth 1 -type d \! -name '.git' \! -name 'doc' \! -name 'po' \! -name 'build' \! -name 'test'); do
+			spellintian $(find "$DIR" -type f)
+		done
+	} | grep -v \
+		-e '^.*: long long (duplicate word) -> long$' \
+		-e '^./apt-pkg/pkgcache.h: ID ID (duplicate word) -> ID$' \
+		-e '^./apt-pkg/contrib/mmap.cc: WorkSpace WorkSpace (duplicate word) -> WorkSpace$' \
+		-e '^./apt-pkg/contrib/md5.cc: z z (duplicate word) -> z$' \
+		-e '^./apt-pkg/metaindex.cc: const const (duplicate word) -> const$' \
+		-e '^./apt-pkg/acquire-method.cc: QueueBack QueueBack (duplicate word) -> QueueBack$' \
+		-e '^./CMake/Translations.cmake: domain domain (duplicate word) -> domain$' \
+		-e '^./CMake/apti18n.h.in: m m (duplicate word) -> m$' \
+		-e '^./CMake/run_if_exists.sh: fi fi (duplicate word) -> fi$' \
+		-e '^./ftparchive/byhash.cc: ByHash ByHash (duplicate word) -> ByHash$' \
+		-e '^./ftparchive/writer.cc: this Packages -> these packages$' \
+		-e '^./ftparchive/byhash.h: ByHash ByHash (duplicate word) -> ByHash$' \
+		-e '^./cmdline/apt-key.in: done done (duplicate word) -> done$' \
+		-e '^./cmdline/apt-key.in: fi fi (duplicate word) -> fi$' \
+		-e '^./cmdline/apt-key.in: echo echo (duplicate word) -> echo$' \
+		-e '^./triehash/.travis.yml: perl perl (duplicate word) -> perl$' \
+		-e '^./triehash/README.md: Performance Performance (duplicate word) -> Performance$' \
+		-e '^./debian/apt.apt-compat.cron.daily: fi fi (duplicate word) -> fi$' \
+		-e '^./debian/apt.auto-removal.sh: done done (duplicate word) -> done$' \
+		-e '^./debian/apt.systemd.daily: fi fi (duplicate word) -> fi$' \
+		-e '^./debian/apt.postinst: fi fi (duplicate word) -> fi$' \
+		-e '^./methods/http.cc: Sz Sz (duplicate word) -> Sz$' \
+		-e '^./methods/ftp.cc: AFMap AFMap (duplicate word) -> AFMap$' \
+		-e '^./dselect/install: fi fi (duplicate word) -> fi$' \
+		|| true
+	echo '### spellintian in testcases:'
+	spellintian $(find test -type f \! -name 'status-*' \! -name 'Packages-*' \! -name '*.deb' \! -name '*.sec' \! -name '*.pub' \! -name '*.db') \
+	| grep -v \
+		-e '^.*: long long (duplicate word) -> long$' \
+		-e '^test/integration/.*: fi fi (duplicate word) -> fi$' \
+		-e '^test/integration/.*: done done (duplicate word) -> done$' \
+		-e '^test/integration/.*: echo echo (duplicate word) -> echo$' \
+		-e '^test/integration/test-00-commands-have-help: moo moo (duplicate word) -> moo$' \
+		-e '^test/integration/test-apt-cache: bar bar (duplicate word) -> bar$' \
+		-e '^test/integration/test-sourceslist-trusted-options: everythingsucceeds everythingsucceeds (duplicate word) -> everythingsucceeds$' \
+		-e '^test/integration/test-sourceslist-trusted-options: everythingfails everythingfails (duplicate word) -> everythingfails$' \
+		-e '^test/integration/test-apt-get-changelog: foo foo (duplicate word) -> foo$' \
+		-e '^test/integration/test-ubuntu-bug-761175-remove-purge: testround testround (duplicate word) -> testround$' \
+		-e '^test/integration/test-apt-get-download: apt apt (duplicate word) -> apt$' \
+		-e '^test/integration/test-apt-showlist-orgroup-in-recommends: zzz zzz (duplicate word) -> zzz$' \
+		-e '^test/integration/test-bug-691453-apt-cache-search-multi-pattern: bar bar (duplicate word) -> bar$' \
+		-e '^test/integration/test-allow: hold hold (duplicate word) -> hold$' \
+		-e '^test/integration/test-apt-by-hash-update: ensureitsbroken ensureitsbroken (duplicate word) -> ensureitsbroken$' \
+		-e '^test/integration/test-apt-source-and-build-dep: foo foo (duplicate word) -> foo$' \
+		|| true
+	echo '### spellintian in documentation:'
+	spellintian doc/*.xml doc/*.txt doc/*.dbk doc/*.ent doc/*.cmake.in doc/xml.add doc/po4a.conf doc/examples/* doc/po/apt-doc.pot po/apt-all.pot README.* COPYING
+
 else
 	echo >&1 "Usage:\t$0 pre-export
+\t$0 pre-build
 \t$0 post-build
 
-If you use »git buildpackage« you can leave these alone as they will
-be run at the right places auto-magically. Otherwise you should use
-»pre-export« to update po and pot files as well as version numbering.
-»post-build« can be used to run some more or less useful checks later on.
+Updating po-files and versions as well as some basic checks are done
+by »pre-export« which needs to be run before package building.
+If you use »gbp buildpackage« you will be notified if you forget.
+»pre-build« and »post-build« can be used to run some more or less
+useful checks automatically run by »gbp« otherwise.
 
 \t$0 library
 \t$0 buildlog filename…
@@ -180,6 +305,11 @@ Both will format the diff properly.
 used by .travis.yml.
 »coverage« does a clean build with the right flags for coverage reporting,
 runs all tests and generates a html report in the end.
+
+\t$0 spellcheckers
+
+»spellcheckers« runs »codespell« and »spellintian« on the appropiate files and
+filters out obvious false positives.
 "
 
 fi
diff --git a/test/integration/test-apt-update-unauth b/test/integration/test-apt-update-unauth
--- a/test/integration/test-apt-update-unauth
+++ b/test/integration/test-apt-update-unauth
@@ -5,35 +5,68 @@
 #
 set -e
 
-TESTDIR=$(readlink -f $(dirname $0))
-. $TESTDIR/framework
+TESTDIR="$(readlink -f "$(dirname "$0")")"
+. "$TESTDIR/framework"
+
+umask 022
 
 setupenvironment
 configarchitecture "i386"
+configcompression '.' 'xz'
 
-insertpackage 'unstable' 'foo' 'all' '1.0'
-insertsource 'unstable' 'foo' 'all' '1.0'
+insertpackage 'unstable' 'foo' 'i386' '1.0'
+insertsource 'unstable' 'foo' 'any' '1.0'
 
-setupaptarchive
+setupaptarchive --no-update
 changetowebserver
 
+# FIXME: 
+#  - also check the unauth -> auth success case, i.e. that all files are
+#    reverified
 runtest() {
     # start unauthenticated
-    find rootdir/var/lib/apt/lists/ -type f | xargs rm -f
-    rm -f aptarchive/dists/unstable/*Release*
-    aptget update -qq
+    rm -rf rootdir/var/lib/apt/lists/
+    find aptarchive/ -name '*Release*' -delete
+
+    testwarning aptget update --allow-insecure-repositories
 
     # become authenticated
     generatereleasefiles
     signreleasefiles
 
-    # and ensure we do download the data again
-    msgtest "Check that the data is check when going to authenticated"
-    if aptget update |grep -q Hit; then
-        msgfail
-    else
+    # move uncompressed away
+    mv aptarchive/dists/unstable/main/binary-i386/Packages \
+        aptarchive/dists/unstable/main/binary-i386/Packages.uncompressed
+
+    # and ensure we re-check the downloaded data
+
+    # change the local packages file
+    PKGS=$(ls rootdir/var/lib/apt/lists/*Packages*)
+    echo "meep" > $PKGS
+    listcurrentlistsdirectory > lists.before
+
+    # update and ensure all is reverted on the hashsum failure
+    testfailure aptget update -o Debug::Acquire::Transaction=1 -o Debug::pkgAcquire::Auth=1 -o Debug::pkgAcquire::worker=0 -o Debug::acquire::http=0
+
+    # ensure we have before what we have after
+    msgtest 'Check rollback on going from' 'unauth -> auth'
+    listcurrentlistsdirectory > lists.after
+    if cmp lists.before lists.after; then
         msgpass
+    else
+	echo >&2
+	echo >&2 '### Output of previous apt-get update ###'
+	cat >&2 rootdir/tmp/testfailure.output || true
+	echo >&2 '### Changes in the lists-directory: ###'
+	diff -u >&2 lists.before lists.after || true
+	echo >&2 '### Contents of the lists-directory: ###'
+	ls -l rootdir/var/lib/apt/lists rootdir/var/lib/apt/lists/partial || true
+	msgfail
     fi
+
+    # move uncompressed back for release file
+    mv aptarchive/dists/unstable/main/binary-i386/Packages.uncompressed \
+        aptarchive/dists/unstable/main/binary-i386/Packages
 }
 
 for COMPRESSEDINDEXES in 'false' 'true'; do
@@ -43,6 +76,5 @@ for COMPRESSEDINDEXES in 'false' 'true'; do
 	else
 		msgmsg 'Run tests with GzipIndexes disabled'
 	fi
-
-        runtest
+	runtest
 done
